{% set version = '0.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-climate4r.hub
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/climate4R.hub/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a2b902f02c258980431944e2c16782e4c4a6e4c9dca992be83a54035ceb8ff48

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-loader
  run:
    - r-base
    - r-loader

test:
  commands:
    - $R -e "library('climate4R.hub')"           # [not win]
    - "\"%R%\" -e \"library('climate4R.hub')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/climate4R
  summary: Enables harmonized access to either remote climate databases stored in the IPCC hub.
  dev_url: https://github.com/SantanderMetGroup/climate4R.hub
  doc_url: https://github.com/SantanderMetGroup/climate4R
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa
    

# Package: climate4R.hub
# Depends: R(>= 3.5.0), loadeR
# Imports: utils
# Suggests: loadeR.ECOMS, transformeR, visualizeR, downscaleR
# Type: Package
# Title: A climate4R package for harmonized data access from the IPCC hub
# Version: 0.0.1
# Date: 2023-06-23
# Authors@R: as.person(c( "Santander Meteorology Group <http://meteo.unican.es> [cph]", "Joaquin Bedia <bediaj@unican.es> [aut,cre]", "Antonio Cofino <antonio.cofino@unican.es> [ctb]", "Matteo de Felice <matteo.defelice@enea.it> [ctb]", "Jesus Fernandez <fernandej@unican.es> [ctb]", "Jose Manuel Gutierrez <gutierjm@unican.es> [ctb]", "Sixto Herrera <herreras@unican.es> [ctb]", "Maialen Iturbide <miturbide@ifca.unican.es> [aut]", "Etienne Tourigny <etienne.tourigny@bsc.es> [ctb]", "Max Tuni <max@predictia.es> [ctb]", "Manuel Vega <manuel.vega@unican.es> [ctb]"))
# BugReports: https://github.com/SantanderMetGroup/climate4R.hub/issues
# URL: https://github.com/SantanderMetGroup/climate4R.hub/wiki
# Encoding: UTF-8
# Description: Enables harmonized access to either remote climate databases stored in the IPCC hub.
# License: file LICENSE
# RoxygenNote: 7.1.2
